# Generated by Django 5.2.7 on 2025-10-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Queryrecordground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userquery', models.TextField()),
                ('gptresponse', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Queryrecordproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userquery', models.TextField()),
                ('gptresponse', models.JSONField()),
            ],
        ),
    ]
