# Generated by Django 5.1.7 on 2025-04-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_orderitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='label',
            field=models.CharField(default='Home', max_length=50),
        ),
    ]
