# Generated by Django 6.0 on 2025-12-14 11:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('types', models.CharField(choices=[('turf', 'Turf'), ('astro', 'Astro'), ('hardcourt', 'Hardcourt'), ('grass', 'Grass')], default='turf', max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='grounds/')),
                ('sporttype', models.CharField(choices=[('football', 'Football'), ('tennis', 'Tennis'), ('badminton', 'Badminton'), ('ground', 'Ground'), ('cricket', 'Cricket'), ('Volleyball', 'Volleyball')], default='turf', max_length=50)),
                ('lattitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('opens', models.BooleanField(default=True)),
                ('batballprovided', models.BooleanField(default=True)),
                ('washroomsavailable', models.BooleanField(default=False)),
                ('Grounddimensions', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings_customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='reservationsession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('expires_at', models.DateTimeField()),
                ('ground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.ground')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='slots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField()),
                ('date', models.DateField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_booked', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('blocked_at', models.DateTimeField(blank=True, null=True)),
                ('ground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='bookings.ground')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.FloatField(blank=True, null=True)),
                ('date', models.DateField()),
                ('transaction_id', models.CharField(max_length=100)),
                ('booked', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('expired', 'Expired'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('price', models.FloatField(default=0.0)),
                ('payment_status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='success', max_length=20)),
                ('refund_amount', models.FloatField(default=0.0)),
                ('cancel_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Tournament_or_normal', models.CharField(default='normal', max_length=20)),
                ('ground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.ground')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('slotsbooked', models.ManyToManyField(to='bookings.slots')),
            ],
        ),
        migrations.CreateModel(
            name='tournamentsession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('session_type', models.CharField(default='full_day', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('ground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.ground')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.reservationsession')),
                ('tournament_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.tournamentsession')),
            ],
        ),
        migrations.CreateModel(
            name='reservedslots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('booked', 'Booked')], default='reserved', max_length=10)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.reservationsession')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.slots')),
            ],
            options={
                'unique_together': {('slot',)},
            },
        ),
        migrations.CreateModel(
            name='reservetournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('booked', 'Booked')], max_length=10)),
                ('ground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.ground')),
                ('slots', models.ManyToManyField(to='bookings.slots')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.tournamentsession')),
            ],
            options={
                'unique_together': {('ground', 'date')},
            },
        ),
    ]
