# Generated by Django 5.2.14 on 2026-05-21 16:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('types', models.CharField(choices=[('turf', 'Turf'), ('ground', 'Ground')], default='turf', max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='grounds/')),
                ('sporttype', models.CharField(choices=[('cricket', 'Cricket'), ('football', 'Football'), ('tennis', 'Tennis'), ('badminton', 'Badminton'), ('volleyball', 'Volleyball'), ('basketball', 'Basketball'), ('hockey', 'Hockey')], default='cricket', max_length=50)),
                ('lattitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('opens', models.BooleanField(default=True)),
                ('batballprovided', models.BooleanField(default=True)),
                ('washroomsavailable', models.BooleanField(default=False)),
                ('Grounddimensions', models.CharField(blank=True, max_length=100, null=True)),
                ('morning_price', models.IntegerField(blank=True, null=True)),
                ('afternoon_price', models.IntegerField(blank=True, null=True)),
                ('evening_price', models.IntegerField(blank=True, null=True)),
                ('night_price', models.IntegerField(blank=True, null=True)),
                ('t_morning_price', models.IntegerField(blank=True, null=True)),
                ('t_afternoon_price', models.IntegerField(blank=True, null=True)),
                ('t_evening_price', models.IntegerField(blank=True, null=True)),
                ('t_night_price', models.IntegerField(blank=True, null=True)),
                ('t_fullday_price', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings_customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='reservationsession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.ground')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='slots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField()),
                ('date', models.DateField()),
                ('shift', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('night', 'Night')], max_length=20)),
                ('is_booked', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('blocked_at', models.DateTimeField(blank=True, null=True)),
                ('ground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='bookings.ground')),
            ],
        ),
        migrations.CreateModel(
            name='tournamentsession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('session_type', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('night', 'Night'), ('full_day', 'Full Day')], default='full_day', max_length=20)),
                ('ground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.ground')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.FloatField()),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.reservationsession')),
                ('tournament_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.tournamentsession')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('transaction_id', models.CharField(max_length=100)),
                ('booked', models.BooleanField(default=False)),
                ('payment_status', models.BooleanField(default=False)),
                ('price', models.FloatField(default=0.0)),
                ('Tournament_or_normal', models.CharField(default='normal', max_length=20)),
                ('refund_amount', models.FloatField(default=0.0)),
                ('cancel_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.ground')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('normal_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.reservationsession')),
                ('slotsbooked', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.slots')),
                ('tournament_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.tournamentsession')),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('transaction_id', models.CharField(max_length=100)),
                ('booked', models.BooleanField(default=False)),
                ('price', models.FloatField(default=0.0)),
                ('payment_status', models.BooleanField(default=False)),
                ('refund_amount', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('Tournament_or_normal', models.CharField(default='normal', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.ground')),
                ('normal_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.reservationsession')),
                ('slotsbooked', models.ManyToManyField(to='bookings.slots')),
                ('tournament_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.tournamentsession')),
            ],
        ),
        migrations.CreateModel(
            name='reservedslots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('booked', 'Booked')], default='reserved', max_length=10)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.reservationsession')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.slots')),
            ],
            options={
                'unique_together': {('slot',)},
            },
        ),
        migrations.CreateModel(
            name='reservetournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('booked', 'Booked')], max_length=10)),
                ('session_type', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('night', 'Night'), ('full_day', 'Full Day')], default='full_day', max_length=20)),
                ('ground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.ground')),
                ('blocked_slots', models.ManyToManyField(related_name='tournament_days', to='bookings.slots')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.tournamentsession')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['reserved', 'booked'])), fields=('ground', 'date'), name='unique_active_tournament_day')],
            },
        ),
    ]
