# Generated by Django 6.0 on 2025-12-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservetournament',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='tournamentsession',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournamentsession',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='reservetournament',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'reserved')), fields=('ground', 'date'), name='unique_active_tournament_day'),
        ),
    ]
