# Generated by Django 4.2.27 on 2026-01-20 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_reservetournament_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reservetournament',
            name='unique_active_tournament_day',
        ),
        migrations.RemoveField(
            model_name='reservetournament',
            name='slots',
        ),
        migrations.AddField(
            model_name='ground',
            name='afternoon_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ground',
            name='evening_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ground',
            name='morning_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ground',
            name='night_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ground',
            name='t_afternoon_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ground',
            name='t_evening_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ground',
            name='t_fullday_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ground',
            name='t_morning_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ground',
            name='t_night_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservetournament',
            name='blocked_slots',
            field=models.ManyToManyField(related_name='tournament_days', to='bookings.slots'),
        ),
        migrations.AddField(
            model_name='reservetournament',
            name='session_type',
            field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('night', 'Night'), ('full_day', 'Full Day')], default='full_day', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slots',
            name='shift',
            field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('night', 'Night')], default='full_day'),
            preserve_default=False,
        ),
        # Remove the FloatField 'session' and re-add as ForeignKey.
        # AlterField cannot cast double precision -> uuid in PostgreSQL,
        # so we drop and recreate instead.
        migrations.RemoveField(
            model_name='orders',
            name='session',
        ),
        migrations.AddField(
            model_name='orders',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.tournamentsession'),
        ),
        migrations.AlterField(
            model_name='slots',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournamentsession',
            name='session_type',
            field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('night', 'Night'), ('full_day', 'Full Day')], default='full_day', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='reservetournament',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['reserved', 'booked'])), fields=('ground', 'date'), name='unique_active_tournament_day'),
        ),
    ]