# Generated by Django 5.2.17 on 2026-08-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_slots_unique_constraint'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reservetournament',
            name='unique_active_tournament_day',
        ),
        migrations.AddField(
            model_name='payment',
            name='razorpay_refund_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='refunded_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddConstraint(
            model_name='reservetournament',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['reserved', 'booked'])), fields=('ground', 'date', 'session_type'), name='unique_active_tournament_day'),
        ),
    ]
