# Generated by Django 4.2.27 on 2026-01-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_reservetournament_unique_active_tournament_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ground',
            name='types',
            field=models.CharField(choices=[('turf', 'Turf'), ('ground', 'Ground')], default='turf', max_length=50),
        ),
        migrations.AlterField(
            model_name='reservetournament',
            name='session_type',
            field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('night', 'Night'), ('full_day', 'Full Day')], default='full_day', max_length=20),
        ),
    ]
