# Generated by Django 5.2.14 on 2026-05-14 12:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_payment_expires_at_payment_stripe_session_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            sql=r"""
DO $$
DECLARE
    constraint_row record;
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'bookings_reservationsession'
          AND column_name = 'id'
          AND data_type = 'bigint'
    ) THEN
        FOR constraint_row IN
            SELECT conrelid::regclass AS table_name, conname
            FROM pg_constraint
            WHERE contype = 'f'
              AND confrelid = 'bookings_reservationsession'::regclass
        LOOP
            EXECUTE format('ALTER TABLE %s DROP CONSTRAINT %I', constraint_row.table_name, constraint_row.conname);
        END LOOP;

        ALTER TABLE bookings_reservationsession ADD COLUMN id_uuid uuid DEFAULT gen_random_uuid();
        ALTER TABLE bookings_payment ADD COLUMN session_id_uuid uuid;
        UPDATE bookings_payment payment
        SET session_id_uuid = session_table.id_uuid
        FROM bookings_reservationsession session_table
        WHERE payment.session_id = session_table.id;

        ALTER TABLE bookings_reservedslots ADD COLUMN session_id_uuid uuid;
        UPDATE bookings_reservedslots reserved_slot
        SET session_id_uuid = session_table.id_uuid
        FROM bookings_reservationsession session_table
        WHERE reserved_slot.session_id = session_table.id;

        ALTER TABLE bookings_payment DROP COLUMN session_id;
        ALTER TABLE bookings_payment RENAME COLUMN session_id_uuid TO session_id;
        ALTER TABLE bookings_reservedslots DROP COLUMN session_id;
        ALTER TABLE bookings_reservedslots RENAME COLUMN session_id_uuid TO session_id;

        FOR constraint_row IN
            SELECT conrelid::regclass AS table_name, conname
            FROM pg_constraint
            WHERE contype = 'p'
              AND conrelid = 'bookings_reservationsession'::regclass
        LOOP
            EXECUTE format('ALTER TABLE %s DROP CONSTRAINT %I', constraint_row.table_name, constraint_row.conname);
        END LOOP;

        ALTER TABLE bookings_reservationsession DROP COLUMN id;
        ALTER TABLE bookings_reservationsession RENAME COLUMN id_uuid TO id;
        ALTER TABLE bookings_reservationsession ALTER COLUMN id SET NOT NULL;
        ALTER TABLE bookings_reservationsession ADD PRIMARY KEY (id);

        ALTER TABLE bookings_payment
            ADD CONSTRAINT bookings_payment_session_id_fk
            FOREIGN KEY (session_id) REFERENCES bookings_reservationsession(id)
            DEFERRABLE INITIALLY DEFERRED;
        ALTER TABLE bookings_reservedslots
            ADD CONSTRAINT bookings_reservedslots_session_id_fk
            FOREIGN KEY (session_id) REFERENCES bookings_reservationsession(id)
            DEFERRABLE INITIALLY DEFERRED;
    END IF;

    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'bookings_tournamentsession'
          AND column_name = 'id'
          AND data_type = 'bigint'
    ) THEN
        FOR constraint_row IN
            SELECT conrelid::regclass AS table_name, conname
            FROM pg_constraint
            WHERE contype = 'f'
              AND confrelid = 'bookings_tournamentsession'::regclass
        LOOP
            EXECUTE format('ALTER TABLE %s DROP CONSTRAINT %I', constraint_row.table_name, constraint_row.conname);
        END LOOP;

        ALTER TABLE bookings_tournamentsession ADD COLUMN id_uuid uuid DEFAULT gen_random_uuid();
        ALTER TABLE bookings_payment ADD COLUMN tournament_session_id_uuid uuid;
        UPDATE bookings_payment payment
        SET tournament_session_id_uuid = session_table.id_uuid
        FROM bookings_tournamentsession session_table
        WHERE payment.tournament_session_id = session_table.id;

        ALTER TABLE bookings_reservetournament ADD COLUMN session_id_uuid uuid;
        UPDATE bookings_reservetournament reserved_tournament
        SET session_id_uuid = session_table.id_uuid
        FROM bookings_tournamentsession session_table
        WHERE reserved_tournament.session_id = session_table.id;

        ALTER TABLE bookings_payment DROP COLUMN tournament_session_id;
        ALTER TABLE bookings_payment RENAME COLUMN tournament_session_id_uuid TO tournament_session_id;
        ALTER TABLE bookings_reservetournament DROP COLUMN session_id;
        ALTER TABLE bookings_reservetournament RENAME COLUMN session_id_uuid TO session_id;

        FOR constraint_row IN
            SELECT conrelid::regclass AS table_name, conname
            FROM pg_constraint
            WHERE contype = 'p'
              AND conrelid = 'bookings_tournamentsession'::regclass
        LOOP
            EXECUTE format('ALTER TABLE %s DROP CONSTRAINT %I', constraint_row.table_name, constraint_row.conname);
        END LOOP;

        ALTER TABLE bookings_tournamentsession DROP COLUMN id;
        ALTER TABLE bookings_tournamentsession RENAME COLUMN id_uuid TO id;
        ALTER TABLE bookings_tournamentsession ALTER COLUMN id SET NOT NULL;
        ALTER TABLE bookings_tournamentsession ADD PRIMARY KEY (id);

        ALTER TABLE bookings_payment
            ADD CONSTRAINT bookings_payment_tournament_session_id_fk
            FOREIGN KEY (tournament_session_id) REFERENCES bookings_tournamentsession(id)
            DEFERRABLE INITIALLY DEFERRED;
        ALTER TABLE bookings_reservetournament
            ADD CONSTRAINT bookings_reservetournament_session_id_fk
            FOREIGN KEY (session_id) REFERENCES bookings_tournamentsession(id)
            DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;
""",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RemoveField(
            model_name='orders',
            name='session',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='status',
        ),
        migrations.RemoveField(
            model_name='reservationsession',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='tournamentsession',
            name='expires_at',
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='normal_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.reservationsession'),
        ),
        migrations.AddField(
            model_name='orders',
            name='tournament_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.tournamentsession'),
        ),
        migrations.AddField(
            model_name='reservationsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ground',
            name='sporttype',
            field=models.CharField(choices=[('cricket', 'Cricket'), ('football', 'Football'), ('tennis', 'Tennis'), ('badminton', 'Badminton'), ('volleyball', 'Volleyball'), ('basketball', 'Basketball'), ('hockey', 'Hockey')], default='cricket', max_length=50),
        ),
        migrations.AlterField(
            model_name='orders',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='orders',
            name='slotsbooked',
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='slots',
            name='shift',
            field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('night', 'Night')], max_length=20),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_price', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.ground')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookings.payment')),
                ('slots', models.ManyToManyField(to='bookings.slots')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('transaction_id', models.CharField(max_length=100)),
                ('booked', models.BooleanField(default=False)),
                ('price', models.FloatField(default=0.0)),
                ('payment_status', models.BooleanField(default=False)),
                ('refund_amount', models.FloatField(default=0.0)),
                ('cancel_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.ground')),
                ('slotsbooked', models.ManyToManyField(to='bookings.slots')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='slotsbooked',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.slots'),
        ),
    ]
